// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {twigHighlight} from "./twig-highlight.js"
const spec_Identifier = {__proto__:null,if:20, endif:26}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fQVOPOOObQQO'#C^OgOPO'#CbOOOO'#Co'#CoOOOO'#Ck'#CkQVOPOOOrQSO'#CcOwQQO,58xOOOO,58|,58|OgOPO,58|O|QSO'#ChOOOO-E6i-E6iO!UQQO,58}OOOO1G.d1G.dOOOO1G.h1G.hO!ZQQO,59SO!`QQO1G.iOOOO1G.n1G.nOOOO7+$T7+$T",
  stateData: "!h~ObOS~ORPOWUO^SO~OSVO~ORPOWYO^SO~OY[O~OT]O~OY[O]_O~OS`O~OZaO~OZbO~ObS~",
  goto: "!XdPPePPPekPPPPqPPwPPP!RXROQTXXQOQTXQWQR^XQTOQXQTZTXXSOQTX",
  nodeNames: "⚠ Template Insert {{ DirectiveContent }} Conditional ConditionalOpen {% Identifier if %} ConditionalClose endif Text",
  maxTerm: 19,
  propSources: [twigHighlight],
  skippedNodes: [0,9],
  repeatNodeCount: 1,
  tokenData: "/`VRpOX#VX^(O^p#Vpq(Oqu#Vuv*Sv!c#V!c!}+[!}#T#V#T#o+[#o#p,Z#p#q#V#q#r.W#r#y#V#y#z(O#z$f#V$f$g(O$g#BY#V#BY#BZ(O#BZ$IS#V$IS$I_(O$I_$I|#V$I|$JO(O$JO$JT#V$JT$JU(O$JU$KV#V$KV$KW(O$KW&FU#V&FU&FV(O&FV;'S#V;'S;=`&o<%lO#VR#^X^PSQOu#Vuv#yv#o#V#o#p$k#p#q#V#q#r#y#r;'S#V;'S;=`&o<%lO#VR$OX^PO#o#V#o#p$k#p#q#V#q#r&z#r;'S#V;'S;=`&o<%l~#V~O#V~~&jR$pZSQOu#Vuv%cv#o#V#o#p%x#p#q#V#q#r#y#r;'S#V;'S;=`&o<%l~#V~O#V~~&uQ%fUO#q%x#r;'S%x;'S;=`&d<%l~%x~O%x~~&jQ%}VSQOu%xuv%cv#q%x#q#r%c#r;'S%x;'S;=`&d<%lO%xQ&gP;=`<%l%xQ&oOSQR&rP;=`<%l#VP&zO^PP'PT^PO#o&z#o#p'`#p;'S&z;'S;=`'x<%lO&zP'cVOu&zv#o&z#p;'S&z;'S;=`'x<%l~&z~O&z~~&uP'{P;=`<%l&zV(Xm^PbUSQOX#VX^(O^p#Vpq(Oqu#Vuv#yv#o#V#o#p$k#p#q#V#q#r#y#r#y#V#y#z(O#z$f#V$f$g(O$g#BY#V#BY#BZ(O#BZ$IS#V$IS$I_(O$I_$I|#V$I|$JO(O$JO$JT#V$JT$JU(O$JU$KV#V$KV$KW(O$KW&FU#V&FU&FV(O&FV;'S#V;'S;=`&o<%lO#VR*XX^PO#o#V#o#p$k#p#q#V#q#r*t#r;'S#V;'S;=`&o<%l~#V~O#V~~&jR*{TZQ^PO#o&z#o#p'`#p;'S&z;'S;=`'x<%lO&zV+e[XS^PSQOu#Vuv#yv!c#V!c!}+[!}#T#V#T#o+[#o#p$k#p#q#V#q#r#y#r;'S#V;'S;=`&o<%lO#VR,`ZSQOu#Vuv-Rv#o#V#o#p-j#p#q#V#q#r#y#r;'S#V;'S;=`&o<%l~#V~O#V~~&uR-WUWPO#q%x#r;'S%x;'S;=`&d<%l~%x~O%x~~&jR-qVRPSQOu%xuv%cv#q%x#q#r%c#r;'S%x;'S;=`&d<%lO%xR.]X^PO#o#V#o#p$k#p#q#V#q#r.x#r;'S#V;'S;=`&o<%l~#V~O#V~~&jR/PTTQ^PO#o&z#o#p'`#p;'S&z;'S;=`'x<%lO&z",
  tokenizers: [0, 1, 2],
  topRules: {"Template":[0,1]},
  specialized: [{term: 9, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 67
})
